// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pandemie.Data;

#nullable disable

namespace pandemie.Migrations
{
    [DbContext(typeof(pandemieContext))]
    [Migration("20240107151442_Vaccin")]
    partial class Vaccin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("pandemie.Models.Producator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VaccinID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VaccinID");

                    b.ToTable("Producator");
                });

            modelBuilder.Entity("pandemie.Models.Vaccin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Data_aprobare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Informatii")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret_achizitie")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.ToTable("Vaccin");
                });

            modelBuilder.Entity("pandemie.Models.Producator", b =>
                {
                    b.HasOne("pandemie.Models.Vaccin", "Vaccin")
                        .WithMany("Producatori")
                        .HasForeignKey("VaccinID");

                    b.Navigation("Vaccin");
                });

            modelBuilder.Entity("pandemie.Models.Vaccin", b =>
                {
                    b.Navigation("Producatori");
                });
#pragma warning restore 612, 618
        }
    }
}
